spring:
  jpa:
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:farm

  servlet:
    multipart:
      max-file-size: 4096KB
      max-request-size: 4096KB
